name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: adamhogle/vault-and-lego
          tags: latest
